# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spok < Formula
  desc "Sans Password or Key (SPoK) - An easier way for remote server authentication."
  homepage "https://github.com/devlup-labs/spok"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/devlup-labs/spok/releases/download/0.1.0/spok_0.1.0_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "271c2948f1d1af1d6018e6e378809dc619484700e4bc53aa90e8a1915de6d6be"

      def install
        bin.install "bin/spok"

        (etc/"spok"/"scripts").install "scripts/configure-spok-server.sh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/devlup-labs/spok/releases/download/0.1.0/spok_0.1.0_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "e4238230b76f342663aae62cb19f3a87b407d043978d9aad14dd99306fadc0cd"

      def install
        bin.install "bin/spok"

        (etc/"spok"/"scripts").install "scripts/configure-spok-server.sh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/devlup-labs/spok/releases/download/0.1.0/spok_0.1.0_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "6f200f76cd23a7eee170d7d40fe8d5e6eed8b93087c00b0554761b8e4657690b"

      def install
        bin.install "bin/spok"

        (etc/"spok"/"scripts").install "scripts/configure-spok-server.sh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devlup-labs/spok/releases/download/0.1.0/spok_0.1.0_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "0f314e44e99a10cdbc63942d826c8ed069d6ce7d8c4a1f3ef23ce5c5f747bd2f"

      def install
        bin.install "bin/spok"

        (etc/"spok"/"scripts").install "scripts/configure-spok-server.sh"
      end
    end
  end
end
