# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spok < Formula
  desc "Sans Password or Key (SPoK) - An easier way for remote server authentication."
  homepage "https://github.com/devlup-labs/spok"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/devlup-labs/spok/releases/download/0.1.0/spok_0.1.0_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "15edce2bf5808027394713b59fbd19b35cbc7eed0814656ed7707e664026fef1"

      def install
        bin.install "bin/spok"

        (etc/"spok"/"scripts").install "scripts/configure-spok-server.sh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/devlup-labs/spok/releases/download/0.1.0/spok_0.1.0_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "10bc0cbe6c5e2ad7b55ddd3c89f23c74923e6e3b85bd8ac898a728e8d9944fc2"

      def install
        bin.install "bin/spok"

        (etc/"spok"/"scripts").install "scripts/configure-spok-server.sh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/devlup-labs/spok/releases/download/0.1.0/spok_0.1.0_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "0163e028b59095d1d7369075259d89f1f20473649c899150fb8114579a99d9b3"

      def install
        bin.install "bin/spok"

        (etc/"spok"/"scripts").install "scripts/configure-spok-server.sh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devlup-labs/spok/releases/download/0.1.0/spok_0.1.0_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "d9ffa4d965c5dbe867dee4d54b32e7503c19c6e10cde95e14b9a17e8161d05fc"

      def install
        bin.install "bin/spok"

        (etc/"spok"/"scripts").install "scripts/configure-spok-server.sh"
      end
    end
  end
end
